name: weather_app
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  dio: ^4.0.4
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_loggy_dio: ^2.0.0+3
  get_it: ^7.2.0
  json_annotation: ^4.4.0
  loggy: ^2.0.1+1
  retrofit: ^3.0.1
  routemaster: ^0.9.5
  rxdata: ^0.5.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  retrofit_generator: ^4.0.0
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
